version: "3"

services: 
  apistoom:
    build: 
     context: .
    ports:
      - "8000:8000"
    volumes:
      - ./apistoom:/apistoom
    command: 
      sh -c "python manage.py runserver 0.0.0.0:8000"
    