# Generated by Django 3.0.8 on 2020-07-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_auto_20200725_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
